2014-12-21 17:11:34,059 - mylogger - C:\blog\blog\app\dao.py - 97 - ERROR - add group error (ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'INSERT INTO "group" (name, create_time) VALUES (?, ?)' ('\xe6\xb5\x8b\xe8\xaf\x95\xe5\x88\x86\xe7\xbb\x841', 1419153094)
2014-12-21 17:11:34,065 - mylogger - C:\blog\blog\app\dao.py - 97 - ERROR - add group error This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'INSERT INTO "group" (name, create_time) VALUES (?, ?)' ('\xe6\xb5\x8b\xe8\xaf\x95\xe5\x88\x86\xe7\xbb\x841', 1419153094)
2014-12-21 17:11:34,065 - mylogger - C:\blog\blog\app\dao.py - 79 - ERROR - get groups error 'BaseQuery' object is not callable 
2014-12-21 17:12:30,423 - mylogger - C:\blog\blog\app\dao.py - 79 - ERROR - get groups error 'BaseQuery' object is not callable 
